Fix https://github.com/riot/riot/issues/2931
riot/compiler pull request #151
Opened 2021-08-07 11:06 UTC by kachurun

2021-08-08 14:08 UTC, GianlucaGuarini requested changes
Thank you @kachurun your patch looks good. Could you please update the small issues I have identified? Could you please also rebase your project in order to get a better commit history? Awsome job ;)

2021-08-08 14:08 UTC, GianlucaGuarini commented on src/index.js
> +  return transformer.bind(this, sourceNode, source, meta)
please change only the code to patch the issue and don't change other stuff not relevant to it

2021-08-08 14:08 UTC, GianlucaGuarini commented on src/index.js
> -    (!sourceNode.nodes && !sourceNode.text)) {
have you already tried adding only `sourceNode.attributes` to the  `(!sourceNode.nodes && !sourceNode.text)` condition? I think it's simpler to understand than the proposed nested patch

2021-08-14 11:13 UTC, kachurun commented on src/index.js
> -    (!sourceNode.nodes && !sourceNode.text)) {
No, it did not work because `(sourceNode.nodes && !sourceNode.nodes.length)` condition evaluates first.

2021-08-14 11:32 UTC, kachurun commented on src/index.js
> +  return transformer.bind(this, sourceNode, source, meta)
Sorry, my habit is to refactor everything in my path

2021-08-14 11:41 UTC, kachurun commented
I can't squash commits for some reasons and I make new PR:
https://github.com/riot/compiler/pull/152

2021-08-14 11:41 UTC, closed without merging