Fix https://github.com/riot/riot/issues/2931
riot/compiler pull request #152
Opened 2021-08-14 11:39 UTC by kachurun

Fix for https://github.com/riot/riot/issues/2931

2021-08-18 10:47 UTC, GianlucaGuarini requested changes
Thank you, there is only something small to update and we can merge it

2021-08-18 10:47 UTC, GianlucaGuarini commented on src/index.js
> +  if (!hasContent) {
Could you please change this if to?

```hasContent ? curry(transformer)(sourceNode, source, meta) : result => result```

2021-08-18 10:47 UTC, GianlucaGuarini commented on src/index.js
> +  if (!hasContent) {
I prefer positive conditions to negative lookups

2021-08-21 13:12 UTC, kachurun commented on src/index.js
> +  if (!hasContent) {
Done

2021-08-22 12:44 UTC, merged